# Name the GitHub Action
name: Deploy via Snowflake CLI

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: '3.8'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout repository
      - name: Checkout GitHub Action
        uses: actions/checkout@v3

      # Install Python
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      # Install Snowflake CLI
      - name: Install Snowflake CLI
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-cli

      # Create Snowflake config
      - name: Create config
        shell: bash
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWCLI_PW }}
        run: |
          mkdir -p ~/.snowflake
          cp config.toml ~/.snowflake/config.toml
          echo "password = \"$SNOWFLAKE_PASSWORD\"" >> ~/.snowflake/config.toml
          chmod 0600 ~/.snowflake/config.toml

      # Deploy the Streamlit app
      - name: Deploy the Streamlit app
        shell: bash
        run: |
          snow streamlit deploy TEST_PROD_STREAMLIT --replace
